### ISSUE TITLE
Hang on repository load.

### ISSUE THREAD

**Issue by notflip** [wtfzdotnet/php-tmdb-api#63]
I'm experimenting with the wrapper and this line 

    $movie = $repository->load(550);

Is causing the whole page to hang on localhost, 
This is the error code

    Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 6: Could not resolve host: api.themoviedb.org

This is my code.

    $token  = new \Tmdb\ApiToken('API_TOKEN');
    $client = new \Tmdb\Client($token);
    $repository = new \Tmdb\Repository\MovieRepository($client);
    $movie = $repository->load(550);

Any idea what might be going wrong? Thanks!

**Comment by wtfzdotnet** [comment]
Please make sure your DNS settings are valid, as the exception message tells you the domain can't be resolved.

**Comment by wtfzdotnet** [comment]
@notflip did you manage to get this issue fixed? :)

**Comment by notflip** [comment]
Yes I did! I think the issue was my vagrant box that didn't have the required dependancies! 
Thank you for this great plugin!

**Comment by wtfzdotnet** [comment]
Sounds like you had your network configured improperly for external access. did you add the proper configuration in your Vagrantfile?

https://docs.vagrantup.com/v2/networking/public_network.html
