### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by NMullen** [wtfzdotnet/php-tmdb-api#73]
I am encountering the above error on line 36 of the class "\Tmdb\HttpClient\Adapter\AbstractAdapter.php"

whilst calling getTvShow($id) in the class Tmdb\Api\TV a var_dump of the response object on line 33 shows an empty body

'''JSON
object(Tmdb\HttpClient\Response)#539 (3) {
  ["body":"Tmdb\HttpClient\Response":private]=>
  string(0) ""
  ["code":"Tmdb\HttpClient\Response":private]=>
  int(404)
  ["headers":"Tmdb\HttpClient\Response":private]=>
  object(Tmdb\Common\ParameterBag)#540 (1) {
    ["parameters":protected]=>
    array(9) {
      ["Cache-Control"]=>
      array(1) {
        [0]=>
        string(21) "public, max-age=36000"
      }
      ["Content-Type"]=>
      array(1) {
        [0]=>
        string(23) "text/html;charset=utf-8"
      }
      ["Date"]=>
      array(1) {
        [0]=>
        string(29) "Tue, 27 Jan 2015 10:44:13 GMT"
      }
      ["Server"]=>
      array(1) {
        [0]=>
        string(5) "nginx"
      }
      ["Status"]=>
      array(1) {
        [0]=>
        string(13) "404 Not Found"
      }
      ["Content-Length"]=>
      array(1) {
        [0]=>
        string(1) "0"
      }
      ["Connection"]=>
      array(1) {
        [0]=>
        string(10) "keep-alive"
      }
      ["X-Cache-Lookup"]=>
      array(1) {
        [0]=>
        string(21) "MISS from GuzzleCache"
      }
      ["X-Cache"]=>
      array(1) {
        [0]=>
        string(21) "MISS from GuzzleCache"
      }
    }
  }
}
'''

**Comment by wtfzdotnet** [comment]
@NMullen , could you post the actual code you are using currently? Just to make sure this should function, when I for example try:
```php
$token  = new \Tmdb\ApiToken(TMDB_API_KEY);
$client = new \Tmdb\Client($token);

$tvShow = $client->getTvApi()->getTvshow(1399);
```
Everything works fine as expected, so some extra input from your end could help :-)
