### ISSUE TITLE
GenreRepository throws fatal error

### ISSUE THREAD

**Issue by webphax** [wtfzdotnet/php-tmdb-api#82]
Hey wtfzdotnet, thanks for this great API wrapper! 

Currently I'm facing an issue with it. When I try to call the Genre Repository via
    $repository = new \Tmdb\Repository\GenreRepository($client);
    $genre      = $repository->getMovies(18);
it throws a fatal error: Call to undefined method Tmdb\Factory\GenreFactory::createMovie() in [...]\vendor\wtfzdotnet\php-tmdb-api\lib\Tmdb\Factory\AbstractFactory.php on line 130

Stacktrace excerpt:
6	0.0950	2030448	Tmdb\Repository\GenreRepository->getMovies( )	..\index.php:26
7	0.1290	2582448	Tmdb\Factory\AbstractFactory->createResultCollection( )	
..\GenreRepository.php:67

Your help is greatly appreciated.

Thanks!

**Comment by wtfzdotnet** [comment]
I'll have a look at this later tonight when I get home from work!

**Comment by wtfzdotnet** [comment]
Could you check which version you are running by the way? :)

**Comment by webphax** [comment]
I'm using version 2.0.3

**Comment by wtfzdotnet** [comment]
@webphax this has been fixed in a6a7783467086f1dfabafd0405ad0028ee36888b, waiting on feedback from Travis to release 2.0.4. Thanks for the report!

**Comment by wtfzdotnet** [comment]
I released 2.0.4 which contains the fix, happy coding!

**Comment by webphax** [comment]
@wtfzdotnet, many thanks, works perfect!

**Comment by wtfzdotnet** [comment]
Anytime! If you have any questions non bug related, feel free to post in the google+ community, or just contact me :)

**Comment by webphax** [comment]
Hi @wtfzdotnet, as the GenreRepository is working now, I'm facing another problem with it. When I try to load the genre model it returns the genre with id = 18 by default:

`$genre_repository = new \Tmdb\Repository\GenreRepository($client);
var_dump($genre_repository->load(878));`
returns 
`object(Tmdb\Model\Genre)[52]
  private 'id' => int 28
  private 'name' => string 'Action' (length=6)`

In this case it seems to work:
`var_dump($genre_repository->getApi()->getGenre(878));`
returns 
`array (size=2)
  'id' => int 878
  'name' => string 'Science Fiction' (length=15)`

Thanks!

**Comment by wtfzdotnet** [comment]
@webphax update to `2.0.5` and your problems will be gone :), can't believe these things are popping up right now. Hope it's a long haul forwards from now on!

**Comment by wtfzdotnet** [comment]
@webphax make that `2.0.6`, getting a bit too used being on `hhvm` I guess :P
